In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("C:\Python\Project\weatherHistory.csv")

# Show the first 5 rows
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [32]:
#remove duplicates, fill missing values, and rename columns.
df = df.drop_duplicates()
df = df.fillna(method='ffill')
df = df.rename(columns={'Formatted Date': 'date', 'Summary': 'summary', 'Precip Type': 'precip_type', 'Temperature (C)': 'temperature_c', 'Apparent Temperature (C)': 'apparent_temperature_c', 'Humidity': 'humidity', 'Wind Speed (km/h)': 'wind_speed_kmh', 'Wind Bearing (degrees)': 'wind_bearing_degrees', 'Visibility (km)': 'visibility_km', 'Loud Cover': 'cloud_cover', 'Pressure (millibars)': 'pressure_millibars'})
df

C:\Users\kamik\AppData\Local\Temp\ipykernel_7452\650792487.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')

,date,summary,precip_type,temperature_c,apparent_temperature_c,humidity,wind_speed_kmh,wind_bearing_degrees,visibility_km,cloud_cover,pressure_millibars,Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [34]:
import pandasql as ps

query = "SELECT AVG(`temperature_c`) as avg_temp FROM df"
result = ps.sqldf(query, locals())
print(result)

    avg_temp
0  11.929692

In [35]:
query = "SELECT date, temperature_c FROM df WHERE temperature_c = (SELECT MAX(temperature_c) FROM df)"
result = ps.sqldf(query, locals())
print(result)

                            date  temperature_c
0  2007-07-22 15:00:00.000 +0200      39.905556

In [38]:
query="SELECT date, precip_type FROM df WHERE precip_type != 'rain'"
result = ps.sqldf(query, locals())
print(result)

                                date precip_type
0      2006-12-13 02:00:00.000 +0100        snow
1      2006-12-13 03:00:00.000 +0100        snow
2      2006-12-13 04:00:00.000 +0100        snow
3      2006-12-13 05:00:00.000 +0100        snow
4      2006-12-13 06:00:00.000 +0100        snow
...                              ...         ...
10707  2016-03-28 05:00:00.000 +0200        snow
10708  2016-03-28 06:00:00.000 +0200        snow
10709  2016-03-28 07:00:00.000 +0200        snow
10710  2016-03-03 03:00:00.000 +0100        snow
10711  2016-03-09 06:00:00.000 +0100        snow

[10712 rows x 2 columns]

In [41]:
df.to_csv("cleaned_weather.csv", index=False)